### ISSUE TITLE
metadata override 

### ISSUE THREAD

**Issue by jb08** [wojtekmach/minitest-metadata#13]
```
minitest/spec.rb:242:in `let': let 'metadata' cannot override a method in Minitest::Spec. Please use another name. 
```

Any workarounds to renaming all existing spec usages of `let(:metadata)`?

**Comment by wojtekmach** [comment]
Hey @jb08, sorry, I don't know the answer to your question off the top of my head. Btw, I don't maintain the project anymore, I'm gonna mark it as such. Sorry about that too!
